package com.news.db.session;

import android.database.sqlite.SQLiteDatabase;

import com.news.db.dao.TABLE_COLLECT;
import com.news.db.dao.TABLE_COLLECTDao;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tABLE_COLLECTDaoConfig;

    private final TABLE_COLLECTDao tABLE_COLLECTDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tABLE_COLLECTDaoConfig = daoConfigMap.get(TABLE_COLLECTDao.class).clone();
        tABLE_COLLECTDaoConfig.initIdentityScope(type);

        tABLE_COLLECTDao = new TABLE_COLLECTDao(tABLE_COLLECTDaoConfig, this);

        registerDao(TABLE_COLLECT.class, tABLE_COLLECTDao);
    }
    
    public void clear() {
        tABLE_COLLECTDaoConfig.getIdentityScope().clear();
    }

    public TABLE_COLLECTDao getTABLE_COLLECTDao() {
        return tABLE_COLLECTDao;
    }

}
