package com.news.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.news.model.bean.gank.CollectBean;
import com.news.model.bean.gank.GankBean;

import java.util.ArrayList;
import java.util.List;

/**
 * Entity mapped to table "TABLE__COLLECT".
 */
public class TABLE_COLLECT {

    private long id;
    /**
     * Not-null value.
     */
    private String User;
    private int year;
    private int month;
    private int day;
    /**
     * Not-null value.
     */
    private String desc;
    private String source;
    private String image;
    /**
     * Not-null value.
     */
    private String type;
    /**
     * Not-null value.
     */
    private String url;
    private String who;

    public TABLE_COLLECT() {
    }

    public TABLE_COLLECT(long id) {
        this.id = id;
    }

    public TABLE_COLLECT(long id, String User, int year, int month, int day, String desc, String source, String image, String type, String url, String who) {
        this.id = id;
        this.User = User;
        this.year = year;
        this.month = month;
        this.day = day;
        this.desc = desc;
        this.source = source;
        this.image = image;
        this.type = type;
        this.url = url;
        this.who = who;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    /**
     * Not-null value.
     */
    public String getUser() {
        return User;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setUser(String User) {
        this.User = User;
    }

    public int getYear() {
        return year;
    }

    public void setYear(int year) {
        this.year = year;
    }

    public int getMonth() {
        return month;
    }

    public void setMonth(int month) {
        this.month = month;
    }

    public int getDay() {
        return day;
    }

    public void setDay(int day) {
        this.day = day;
    }

    /**
     * Not-null value.
     */
    public String getDesc() {
        return desc;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    /**
     * Not-null value.
     */
    public String getType() {
        return type;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Not-null value.
     */
    public String getUrl() {
        return url;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setUrl(String url) {
        this.url = url;
    }

    public String getWho() {
        return who;
    }

    public void setWho(String who) {
        this.who = who;
    }

    public GankBean toGankBean() {
        GankBean gank = new GankBean();
        gank.setDesc(getDesc());
        gank.setSource(getSource());
        gank.setImages(toImageList());
        gank.setType(getType());
        gank.setUrl(getUrl());
        gank.setWho(getWho());

        return gank;
    }

    public CollectBean toCollectBean() {
        CollectBean collect = new CollectBean();
        collect.set_id(getId());
        collect.setUser(getUser());
        collect.setYear(getYear());
        collect.setMonth(getMonth());
        collect.setDay(getDay());
        collect.setCollect(toGankBean());
        return collect;
    }

    public List<String> toImageList() {
        List<String> images = new ArrayList<>();
        String[] items = getImage().split(",");
        for (String item : items) {
            images.add(item);
        }
        return images;
    }


}
